---
classification: webapp
production:
  tier: 3
  url: 
  hosting_platform: Vercel
performance_monitoring: []
error_monitoring: []
continuous_integration: []
bug_tracking: []
documentation: []
deployment: []
languages:
  - name: JavaScript
frameworks:
  - name: React
    version: 17.0.1
logging: []
